----------------Livro----------------------
CREATE TABLE LIVRO
(
	IDLIVRO 	NUMBER(5) PRIMARY KEY,
	TITULO		VARCHAR2(80) NOT NULL,
	AUTOR		VARCHAR2(60) NOT NULL,
	ANO			NUMBER(4),
	STATUS		CHAR(1) DEFAULT 'D',
	CONSTRAINT LIVRO_STATUS_CHK CHECK (STATUS IN ('D','E')),
	CONSTRAINT LIVRO_ANO_CHK CHECK (ANO > 1900)
	--D = Disponivel / E = Emprestado 
);
------------------Leitor---------------------
CREATE TABLE LEITOR 
(
	IDLEITOR	NUMBER(5) PRIMARY KEY,
	NOME		VARCHAR2(60) NOT NULL,
	TELEFONE	VARCHAR2(20),
	EMAIL		VARCHAR2(80) UNIQUE
);
--------------------Emprestimo-----------------
CREATE TABLE EMPRESTIMO
(
	IDEMP		NUMBER(5) PRIMARY KEY,
	DATAEMP		DATE	NOT NULL,
	DATADEV		DATE,
	IDLIVRO		NUMBER(5) REFERENCES LIVRO(IDLIVRO),
	IDLEITOR	NUMBER(5) REFERENCES LEITOR(IDLEITOR)
	--Relacionamento:   Emprestimo --> Livro, Leitor
);